ALTER TABLE projects ADD COLUMN IF NOT EXISTS sort_order INT DEFAULT 0 NOT NULL;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS category VARCHAR(32) DEFAULT 'APPLICATION' NOT NULL;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS push_enabled BOOLEAN DEFAULT TRUE NOT NULL;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS clean_command VARCHAR(2000);
